/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Classroom;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author hasee
 */
public class AddClassroomResMenu extends javax.swing.JFrame {
    private Classroom clas;
    private PresentationCtrl presentationctrl;
    private JTextField numField;
    private JTextField dIniField;
    private JTextField dEndField;
    private JTextField hIniField;
    private JTextField hEndField;
    
    private JLabel numLabel;
    private JLabel dIniLabel;
    private JLabel dEndLabel;    
    private JLabel hIniLabel;
    private JLabel hEndLabel;
    
    /**
     * Creates new form addResMenu
     */

    
    public AddClassroomResMenu(PresentationCtrl pre) {
        initComponents();
        presentationctrl = pre;
        this.clas = clas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Aula:");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banejar grup", "Banejar assignatura", "Banejar hora" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(747, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
        switch (comboBox.getSelectedIndex()) {
            case 0:
                 numLabel = new JLabel("Introdueixi el numero del grup que vol bloquejar");
                 dIniLabel = new JLabel("Introdueixi el primer dia a bloquejar");
                 dEndLabel = new JLabel("Introdueixi el darrer dia a bloquejar");
                 hIniLabel = new JLabel("Introdueixi la primera hora a bloquejar");
                 hEndLabel = new JLabel("Introdueixi la darrera hora a bloquejar");
                numField = new JTextField("");
                dIniField = new JTextField("");
                dEndField = new JTextField("");
                hIniField = new JTextField("");
                hEndField = new JTextField("");
                dIniLabel.setLocation(40,125);
                dIniLabel.setSize(300, 20);
                numLabel.setLocation(40, 75);
                numLabel.setSize(300,20);
                
                dIniField.setLocation(40,150);
                dIniField.setSize(300, 20);
                numField.setLocation(40,100);
                numField.setSize(300,20);
                getContentPane().add(dIniLabel);
                getContentPane().add(dIniField);
                getContentPane().add(numLabel);
                getContentPane().add(numField);
                this.setSize(500, 500);
                break;
            case 1:
                break;
            case 2:
                break;
            case 3:
                break;
        }
    }//GEN-LAST:event_comboBoxActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        JLabel dIniLabel = new JLabel("Introdueixi el primer dia a bloquejar");
        dIniField = new JTextField("");
        dIniLabel.setLocation(40,100);
        dIniLabel.setSize(300, 20);
        dIniField.setLocation(40,125);
        dIniField.setSize(300, 20);
        getContentPane().add(dIniLabel);
        getContentPane().add(dIniField);
        this.setSize(500, 500);
    }//GEN-LAST:event_formWindowActivated

    public void setClass(Classroom clas) {
        this.clas = clas;
    }

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
