/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Group;
import domain.Subject;
import javax.swing.JOptionPane;

/**
 *
 * @author hasee
 */
public class AddGroup extends javax.swing.JFrame {
    private PresentationCtrl presentationctrl;
    private Subject sub;
    /**
     * Creates new form AddGroup
     */
    public AddGroup(PresentationCtrl pre, Subject sub) {
        initComponents();
        presentationctrl = pre;
        this.sub = sub;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hIniSlider = new javax.swing.JSlider();
        hEndLabel = new javax.swing.JLabel();
        hEndSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        GroupNum = new javax.swing.JTextField();
        dIniLabel = new javax.swing.JLabel();
        dIniBox = new javax.swing.JComboBox<>();
        dEndLabel = new javax.swing.JLabel();
        dEndBox = new javax.swing.JComboBox<>();
        hIniLabel = new javax.swing.JLabel();
        hIniHLabel = new javax.swing.JLabel();
        hEndHLabel = new javax.swing.JLabel();
        addClassroom = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Enrolled = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hIniSlider.setMaximum(23);
        hIniSlider.setValue(8);
        hIniSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hIniSliderStateChanged(evt);
            }
        });

        hEndLabel.setText("Darrera hora útil de l'aula:");
        hEndLabel.setToolTipText("");

        hEndSlider.setMaximum(23);
        hEndSlider.setToolTipText("");
        hEndSlider.setValue(20);
        hEndSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hEndSliderStateChanged(evt);
            }
        });

        jLabel1.setText("Numero del grup:");

        GroupNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupNumActionPerformed(evt);
            }
        });

        dIniLabel.setText("Primer día útil de l'aula:");

        dIniBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dilluns", "Dimarts", "Dimecres", "Dijous", "Dissabte", "Diumenje" }));

        dEndLabel.setText("Darrer día útil de l'aula:");

        dEndBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dilluns", "Dimarts", "Dimecres", "Dijous", "Dissabte", "Diumenje" }));
        dEndBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dEndBoxActionPerformed(evt);
            }
        });

        hIniLabel.setText("Primera hora útil de l'aula:");

        hIniHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hIniHLabel.setText("8");

        hEndHLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hEndHLabel.setText("20");
        hEndHLabel.setToolTipText("");

        addClassroom.setText("Afegir");
        addClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassroomActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de inscrits en el grup:");

        Enrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrolledActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addClassroom)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hEndSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(hIniSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(hEndLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hIniHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hEndHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Enrolled, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hIniLabel)
                            .addComponent(dEndLabel)
                            .addComponent(dIniLabel)
                            .addComponent(dIniBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GroupNum, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GroupNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enrolled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dIniLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dIniBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dEndLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hIniLabel)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hIniSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hEndLabel))
                    .addComponent(hIniHLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hEndHLabel)
                    .addComponent(hEndSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addClassroom)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hIniSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hIniSliderStateChanged
        // TODO add your handling code here:
        hIniHLabel.setText(hIniSlider.getValue()+"");
    }//GEN-LAST:event_hIniSliderStateChanged

    private void hEndSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hEndSliderStateChanged
        // TODO add your handling code here:
        hEndHLabel.setText(hEndSlider.getValue()+"");
    }//GEN-LAST:event_hEndSliderStateChanged

    private void GroupNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GroupNumActionPerformed

    private void dEndBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dEndBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dEndBoxActionPerformed

    private void addClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassroomActionPerformed
        // TODO add your handling code here:
        int enrolled = Integer.parseInt(Enrolled.getText());;
        int num = Integer.parseInt(GroupNum.getText());
        int dIni = Integer.parseInt(dIniBox.getSelectedIndex()+"");
        int dEnd = Integer.parseInt(dEndBox.getSelectedIndex()+"");
        int hIni = Integer.parseInt(hIniHLabel.getText());
        int hEnd = Integer.parseInt(hEndHLabel.getText());
        if (dIni > dEnd)
        JOptionPane.showMessageDialog(this, "El darrer día útil ha de\nser el mateix dia o \nposterior al inicial", "Atenció:", JOptionPane.WARNING_MESSAGE);
        if (hIni >= hEnd)
        JOptionPane.showMessageDialog(this, "La darrera hora útil ha de\nser posterior a la primera", "Atenció:", JOptionPane.WARNING_MESSAGE);
        else {
            presentationctrl.addGroup(sub, num, dIni, dEnd, hIni, hEnd, enrolled);
            presentationctrl.SwitchFromAGtoGM();
        }
    }//GEN-LAST:event_addClassroomActionPerformed

    private void EnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrolledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnrolledActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Enrolled;
    private javax.swing.JTextField GroupNum;
    private javax.swing.JButton addClassroom;
    private javax.swing.JComboBox<String> dEndBox;
    private javax.swing.JLabel dEndLabel;
    private javax.swing.JComboBox<String> dIniBox;
    private javax.swing.JLabel dIniLabel;
    private javax.swing.JLabel hEndHLabel;
    private javax.swing.JLabel hEndLabel;
    private javax.swing.JSlider hEndSlider;
    private javax.swing.JLabel hIniHLabel;
    private javax.swing.JLabel hIniLabel;
    private javax.swing.JSlider hIniSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
