/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.GroupSubject;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Raakhuga
 */
public class GroupSubjectInfo extends javax.swing.JFrame {
    private PresentationCtrl presentationctrl;
    private GroupSubject groupsubject = null;
    /**
     * Creates new form GroupSubjectInfo
     */
    public GroupSubjectInfo(PresentationCtrl presentationctrl) {
        initComponents();
        this.presentationctrl = presentationctrl;
    }

    public void setGroupSubject(GroupSubject groupsubject) {
        this.groupsubject = groupsubject;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        JLabel aux = new JLabel("Grup: " + groupsubject.getNumGroup() + "Assignatura: " + groupsubject.getNameSubject());
        aux.setSize(500, 500);
        aux.setLocation(0, 0);
        getContentPane().add(aux);
        JButton backButton = new JButton("enrere");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentationctrl.SwitchFromGSItoCTT();
            }
        });
        backButton.setSize(80,40);
        backButton.setLocation(400,400);
        getContentPane().add(backButton);
        this.setSize(500,500);
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
