/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import domain.Group;
import domain.Subject;
import java.util.List;

/**
 *
 * @author hasee
 */
public class GroupMenu extends javax.swing.JFrame {
    private Subject mSub;
    private PresentationCtrl presentationctrl;
    /**
     * Creates new form GroupMenu
     */
    public GroupMenu(Subject sub, PresentationCtrl presentationctrl) {
        initComponents();
        mSub = sub;
        presentationctrl = presentationctrl;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        modifybottom = new javax.swing.JButton();
        DeleteBottom = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        GroupList = new javax.swing.JList<>();
        detall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel2.setText("Grup");

        jButton2.setText("Afegir Grup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClassroomActionPerformed(evt);
            }
        });

        modifybottom.setText("Modificar Grup");
        modifybottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifybottomActionPerformed(evt);
            }
        });

        DeleteBottom.setText("Esborrar Grup");
        DeleteBottom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBottomActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(GroupList);

        detall.setText("Veure detall del grup");
        detall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeleteBottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detall, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifybottom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(detall)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(modifybottom)
                .addGap(18, 18, 18)
                .addComponent(DeleteBottom)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBottomActionPerformed
        // TODO add your handling code here:
        int index = GroupList.getSelectedIndex();
        List<Group> grouplist = presentationctrl.getGroup(mSub);
        presentationctrl.removeGroup(grouplist.get(index), mSub);
        GroupList.setModel(presentationctrl.getGroupsRefs(mSub));
        jScrollPane2.setViewportView(GroupList);
    }//GEN-LAST:event_DeleteBottomActionPerformed

    private void modifybottomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifybottomActionPerformed
        // TODO add your handling code here:
        int index = GroupList.getSelectedIndex();
        List<Group> groupList = presentationctrl.getGroup(mSub);
        presentationctrl.SwitchFromGMtoMG(groupList.get(index));
    }//GEN-LAST:event_modifybottomActionPerformed

    private void AddClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClassroomActionPerformed
        // TODO add your handling code here:
        presentationctrl.SwitchFromGMtoAG(mSub);

    }//GEN-LAST:event_AddClassroomActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        GroupList.setModel(presentationctrl.getGroupsRefs(mSub));
        jScrollPane2.setViewportView(GroupList);       
    }//GEN-LAST:event_formWindowActivated

    private void detallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallActionPerformed
        // TODO add your handling code here:
        int index = GroupList.getSelectedIndex();
        List<Group> groupList = presentationctrl.getGroup(mSub);
        presentationctrl.SwitchFromGMtosGM(groupList.get(index));

    }//GEN-LAST:event_detallActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBottom;
    private javax.swing.JList<String> GroupList;
    private javax.swing.JButton detall;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifybottom;
    // End of variables declaration//GEN-END:variables
}
